import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

function readSource(relPath: string): string {
  const url = new URL(relPath, import.meta.url);
  return readFileSync(fileURLToPath(url), "utf-8");
}

function readJson(relPath: string): unknown {
  return JSON.parse(readSource(relPath));
}

describe("group_bridge settings placement", () => {
  it("group bridges is a recognized group settings tab without a global group_bridge tab", () => {
    expect(readSource("./types.ts")).toContain('| "connections"');
    expect(readSource("./types.ts")).not.toContain('| "group_bridge"');
    expect(readSource("./settingsLastLocation.ts")).toContain('"connections"');
    expect(readSource("./settingsLastLocation.ts")).not.toContain('"group_bridge"');
  });

  it("SettingsModal registers group Group Bridges without an empty Global Group Bridge page", () => {
    const src = readSource("../../SettingsModal.tsx");
    expect(src).toContain('id: "connections"');
    expect(src).toContain('activeTab === "connections"');
    expect(src).not.toContain('id: "group_bridge"');
    expect(src).not.toContain('activeTab === "group_bridge"');
    expect(src).not.toContain("GroupBridgeRegistrationSection");
    expect(src).toContain("GroupBridgeConnectionsSection");
  });

  it("WebAccessTab no longer embeds the group_bridge form", () => {
    const src = readSource("./WebAccessTab.tsx");
    expect(src).not.toContain("GroupBridgeRegistrationSection");
  });

  it("group Connections owns Group Bridge session pairing and always filters by current group", () => {
    const src = readSource("./GroupBridgeConnectionsSection.tsx");
    expect(src).toContain("GroupBridgePairingSection");
    expect(src).toContain("groupId");
    expect(src).toContain("fetchGroupBridgePairingRequests(groupId)");
    expect(src).toContain("fetchGroupBridgeTrusts(groupId)");
    expect(src).toContain("fetchGroupBridgePairingOutbounds(groupId)");
    expect(src).not.toContain("fetchGroupBridgeStatus(groupId)");
  });

  it("group Connections syncs submitted and pending outbound requests on refresh", () => {
    const src = readSource("./GroupBridgeConnectionsSection.tsx");
    expect(src).toContain("projectSyncableOutbounds");
    expect(src).toContain("syncGroupBridgePairingOutbound(outbound.outbound_id)");
    expect(src).not.toContain('String(outbound.status || "") === "submitted"');
  });

  it("Group Bridge session pairing section does not expose direct registration fields or call direct register", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).not.toContain("Remote URL");
    expect(src).not.toContain("Credential reference");
    expect(src).not.toContain("Remote group URL");
    expect(src).not.toContain("DHT");
    expect(src).not.toContain("relay");
    expect(src).not.toContain("hole punching");
    expect(src).not.toContain("registerGroupBridge");
    expect(src).toContain("createGroupBridgePairingInvite");
    expect(src).toContain("createGroupBridgeRemotePairingRequest");
    expect(src).toContain("approveGroupBridgePairingRequest");
  });

  it("Group Bridge session connection info copy uses the shared clipboard fallback", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain("copyTextToClipboard");
    expect(src).not.toContain("navigator.clipboard?.writeText");
  });

  it("Group Bridge session pairing is cross-instance first and demotes same-instance codes", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain('t("group_bridge.connectRemoteCcccGroup")');
    expect(src).toContain('t("group_bridge.issuerEndpoint")');
    expect(src).toContain('t("group_bridge.issuerEndpointLocalOnlyHelp")');
    expect(src).toContain('t("group_bridge.sameInstanceFallbackDetected")');
    expect(src).toContain('t("group_bridge.sameInstanceFallbackHelp")');
    expect(src).toContain("isSameInstancePairingInput");
    const modelSrc = readSource("./groupBridgePairingModel.ts");
    expect(modelSrc).toContain("issuer_endpoint");
    expect(modelSrc).toContain("expires_at");
    expect(modelSrc).toContain("nonce");
    expect(modelSrc).toContain("integrity");
    expect(src).not.toContain('placeholder="ABCD-1234"');
  });

  it("Group Bridge session connection info is generated by the backend after invite creation", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain("normalizeIssuerEndpoint(issuerEndpoint)");
    expect(src).toContain("createGroupBridgePairingConnectionInfo");
    expect(src.indexOf("createGroupBridgePairingInvite")).toBeLessThan(src.indexOf("createGroupBridgePairingConnectionInfo"));
    expect(src).not.toContain("assertSha256Available();");
    expect(src).not.toContain("crypto.subtle.digest");
    expect(src).toContain('t("group_bridge.issuerEndpointInvalid")');
    expect(src).toContain("userFacingPairingErrorKey");
    expect(src).not.toContain('setInviteError(infoResp.error.message || t("group_bridge.createInviteFailed"))');
  });

  it("Group Bridge session connection info includes the current group title for remote display", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain("issuerGroupTitle");
    expect(src).toContain("issuerGroupTitle: currentGroupTitle || currentGroupId");
  });

  it("Group Bridge session pairing submits remote issuer payloads through the remote pairing endpoint", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain("parsed.isRemote && parsed.payload");
    expect(src).toContain("createGroupBridgeRemotePairingRequest");
    expect(src).toContain('t("group_bridge.remotePayloadDetected")');
    expect(src).toContain('t("group_bridge.remotePayloadTarget"');
  });

  it("Group Bridge session pairing revocation invalidates composer Group Bridge route suggestions", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    const revokeStart = src.indexOf("const revokeTrustedPeer");
    expect(revokeStart).toBeGreaterThan(0);
    const revokeSrc = src.slice(revokeStart, src.indexOf("const deleteOutbound", revokeStart));
    expect(revokeSrc).toContain("publishGroupBridgePairingChanged(currentGroupId)");
    expect(revokeSrc.indexOf("revokeGroupBridgeTrust(tid)")).toBeLessThan(revokeSrc.indexOf("publishGroupBridgePairingChanged(currentGroupId)"));
  });

  it("Group Bridge session pairing section uses the current group without local group selection", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain("currentGroupId");
    expect(src).not.toContain("setSelectedGroupId");
    expect(src).not.toContain('t("group_bridge.localGroup")');
    expect(src).not.toContain('t("group_bridge.selectGroup")');
    expect(src).not.toContain('t("group_bridge.peerGroupId")');
  });

  it("Group Bridge session pairing is an approval workbench, not a direct registration form", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain('useTranslation("settings")');
    expect(src).toContain('t("group_bridge.connectRemoteCcccGroup")');
    expect(src).toContain('t("group_bridge.createConnectionInfo")');
    expect(src).toContain('t("group_bridge.pasteConnectionInfo")');
    expect(src).toContain('t("group_bridge.pendingBadge")');
    expect(src).toContain('t("group_bridge.trustedBadge")');
    expect(src).toContain('t("group_bridge.revokeTrust")');
    expect(src).not.toContain("This node");
    expect(src).not.toContain("Create invite");
    expect(src).not.toContain("Submit pairing request");
    expect(src).not.toContain("Incoming requests");
    expect(src).not.toContain("Trusted peers");
    expect(src).not.toContain("Invite another CCCC");
    expect(src).not.toContain("Join with a pairing code");
    expect(src).not.toContain("invite/request metadata, not direct registration");
    expect(src).toContain("<details");
  });

  it("trusted remote groups expose agent target ids without default peer or endpoint noise", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain('t("group_bridge.copyRecipientIdentifier"');
    expect(src).toContain("formatRecipientIdentifier");
    expect(src).toContain('t("group_bridge.remoteAccessToThisGroup"');
    expect(src).toContain('t("group_bridge.thisGroupAccessToRemote"');
    expect(src).toContain('t("group_bridge.refreshRemoteInfo"');
    expect(src).toContain('t("group_bridge.unknownAccess"');
    expect(src).toContain("remoteAccessKnown");
    expect(src).toContain("remoteAccessDescriptions");
    expect(src).not.toContain('t("group_bridge.remoteCccc"');
    expect(src).not.toContain('t("group_bridge.unknownCccc"');
    expect(src).not.toContain('t("group_bridge.remotePeerId"');
    expect(src).not.toContain('t("group_bridge.remoteEndpoint"');
  });

  it("Group Bridge session pairing puts workbench actions before local diagnostics", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain('t("group_bridge.localDiagnostics")');
    expect(src.indexOf('t("group_bridge.connectRemoteCcccGroup")')).toBeLessThan(src.indexOf('t("group_bridge.localDiagnostics")'));
    expect(src.indexOf('t("group_bridge.createConnectionInfo")')).toBeLessThan(src.indexOf('t("group_bridge.localDiagnostics")'));
    expect(src.indexOf('t("group_bridge.pasteConnectionInfo")')).toBeLessThan(src.indexOf('t("group_bridge.localDiagnostics")'));
    expect(src.indexOf('t("group_bridge.incomingRequests")')).toBeLessThan(src.indexOf('t("group_bridge.localDiagnostics")'));
    expect(src.indexOf('t("group_bridge.trustedRemoteGroups")')).toBeLessThan(src.indexOf('t("group_bridge.localDiagnostics")'));
  });

  it("Group Bridge session pairing uses local identity as request metadata instead of requester peer input", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    expect(src).toContain("requesterPeerId: localPeerId");
    expect(src).not.toContain("setRequestPeerId");
    expect(src).not.toContain('t("group_bridge.yourPeerId")');
  });

  it("Group Bridge session diagnostics do not present invite metadata addresses as local addresses", () => {
    const src = readSource("./GroupBridgePairingSection.tsx");
    const diagnosticsStart = src.indexOf('t("group_bridge.localDiagnostics")');
    expect(diagnosticsStart).toBeGreaterThan(0);
    const diagnosticsSrc = src.slice(diagnosticsStart);
    expect(diagnosticsSrc).toContain('t("group_bridge.sessionTransport")');
    expect(diagnosticsSrc).toContain('t("group_bridge.sessionTransportManaged")');
    expect(diagnosticsSrc).not.toContain("multiaddrs.join");
    expect(diagnosticsSrc).not.toContain("multiaddrsText");
  });

  it("Group Bridge Settings user-facing copy lives in settings locale files", () => {
    const locales = [
      readJson("../../../i18n/locales/en/settings.json"),
      readJson("../../../i18n/locales/zh/settings.json"),
      readJson("../../../i18n/locales/ja/settings.json"),
    ] as Array<{ group_bridge?: Record<string, unknown> }>;
    for (const locale of locales) {
      expect(locale.group_bridge).toBeTruthy();
      expect(locale.group_bridge?.connectRemoteCcccGroup).toBeTruthy();
      expect(locale.group_bridge?.createConnectionInfo).toBeTruthy();
      expect(locale.group_bridge?.issuerEndpoint).toBeTruthy();
      expect(locale.group_bridge?.issuerEndpointHelp).toBeTruthy();
      expect(locale.group_bridge?.issuerEndpointLocalOnlyHelp).toBeTruthy();
      expect(locale.group_bridge?.issuerEndpointInvalid).toBeTruthy();
      expect(locale.group_bridge?.unsafeIssuerEndpointBlocked).toBeTruthy();
      expect(locale.group_bridge?.pasteConnectionInfo).toBeTruthy();
      expect(locale.group_bridge?.remotePayloadPlaceholder).toBeTruthy();
      expect(locale.group_bridge?.remotePayloadDetected).toBeTruthy();
      expect(locale.group_bridge?.remotePayloadTarget).toBeTruthy();
      expect(locale.group_bridge?.sameInstanceFallbackDetected).toBeTruthy();
      expect(locale.group_bridge?.sameInstanceFallbackHelp).toBeTruthy();
      expect(locale.group_bridge?.incomingRequests).toBeTruthy();
      expect(locale.group_bridge?.trustedRemoteGroups).toBeTruthy();
      expect(locale.group_bridge?.trustedRemoteGroupsHelp).toBeTruthy();
      expect(locale.group_bridge?.pendingBadge).toBeTruthy();
      expect(locale.group_bridge?.trustedBadge).toBeTruthy();
      expect(locale.group_bridge?.copyRecipientIdentifier).toBeTruthy();
      expect(locale.group_bridge?.copyRecipientIdentifierDone).toBeTruthy();
      expect(locale.group_bridge?.copyRecipientIdentifierManual).toBeTruthy();
      expect(locale.group_bridge?.remoteAccessToThisGroup).toBeTruthy();
      expect(locale.group_bridge?.remoteAccessToThisGroupHelp).toBeTruthy();
      expect(locale.group_bridge?.thisGroupAccessToRemote).toBeTruthy();
      expect(locale.group_bridge?.thisGroupAccessToRemoteHelp).toBeTruthy();
      expect(locale.group_bridge?.refreshRemoteInfo).toBeTruthy();
      expect(locale.group_bridge?.refreshRemoteInfoFailed).toBeTruthy();
      expect(locale.group_bridge?.unknownAccess).toBeTruthy();
      expect(locale.group_bridge?.remoteAccessDescriptions).toBeTruthy();
      expect(locale.group_bridge?.localDiagnostics).toBeTruthy();
      expect(locale.group_bridge?.localDiagnosticsHelp).toBeTruthy();
      expect(locale.group_bridge?.sessionTransport).toBeTruthy();
      expect(locale.group_bridge?.sessionTransportManaged).toBeTruthy();
      expect(locale.group_bridge?.legacyHttpTitle).toBeUndefined();
      expect(locale.tabs?.connections).toBeTruthy();
      expect(locale.tabs?.group_bridge).toBeUndefined();
    }
  });
});
